#@ load("@ytt:data", "data")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      x: 1
  template:
    metadata:
      labels:
        x: 1
    spec:
      containers:
      - name: default
        image: nginx
